# Generated by Django 5.1.3 on 2024-12-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='manga_covers/'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='genre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='manga',
            name='total_chapters',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
