# Generated by Django 5.1.3 on 2024-12-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.CharField(choices=[('Publishing', 'Publishing'), ('Finished', 'Finished')], max_length=20),
        ),
    ]
