# Generated by Django 5.1.3 on 2024-12-20 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_alter_manga_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='chapters_read',
        ),
    ]
